language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4

sudo: false

script:
 - cd test
 - PYTHONPATH=.. python test_demjson.py

after_script:
 - pip install pep8 pyflakes
 - pep8 --statistics --count .
 - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
