language: python

python:
 - 2.7
 - 3.6
 - 3.5
 - 3.4
 - pypy3
 - pypy

sudo: false

script:
 - python setup.py install
 - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then 2to3 -w demjson.py; fi
 - cd test
 - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then 2to3 -w test_demjson.py; fi
 - PYTHONPATH=.. python test_demjson.py

after_script:
 - pip install pycodestyle pyflakes
 - pyflakes . | tee >(wc -l)
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
  allow_failures:
   - python: pypy3
