language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - 3.5

sudo: false

script:
 - python setup.py install
 - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then 2to3 -w demjson.py; fi
 - cd test
 - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then 2to3 -w test_demjson.py; fi
 - PYTHONPATH=.. python test_demjson.py

after_script:
 - pip install pep8 pyflakes
 - pep8 --statistics --count .
 - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
  allow_failures:
   - python: pypy3
   - python: 3.2
   - python: 3.3
   - python: 3.4
   - python: 3.5
